caliper:
    benchconfig: caliper/benchconfig.yaml
    networkconfig: caliper/networkconfig.yaml
    txupdatetime: 10000
    report:
        path: report.html
    logging:
        template: '%timestamp% | %level% | %module% | %message%%metadata%'
        formats:
            timestamp: 'YYYY-MM-DD_HH:mm:ss.SSS ZZ'
            label: false
            json: false
            pad: false
            align: false
            attributeformat:
                level:
                label:
                module:
            colorize: false
        targets:
            console:
                target: console
                enabled: true
                options:
                    level: info
            file:
                target: file
                enabled: false
    flow:
        skip:
            start: true
            init: true
            install: true
            test: false
            end: true
    worker:
        remote: true
        communication:
            method: mqtt
            address: mqtt://mosquitto:1883
    fabric:
        latencythreshold: 0.1
        sleepafter:
            createchannel: 5000
            joinchannel: 5000
            instantiatechaincode: 5000
        timeout:
            chaincodeinstantiate: 600000
            chaincodeinstantiateevent: 300000
            invokeorquery: 60000