General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /etc/hyperledger/msp/orderer/tls/server.key
    Certificate: /etc/hyperledger/msp/orderer/tls/server.crt
    RootCAs:
    - /etc/hyperledger/msp/orderer/tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  Cluster:
    SendBufferSize: 10
    ClientCertificate: /etc/hyperledger/msp/orderer/tls/server.crt
    ClientPrivateKey: /etc/hyperledger/msp/orderer/tls/server.key
    ListenPort:
    ListenAddress:
    ServerCertificate:
    ServerPrivateKey:
  LocalMSPDir: /etc/hyperledger/msp/orderer/msp
  LocalMSPID: OrdererMSP
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  Authentication:
    TimeWindow: 15m
  BootstrapMethod: file
  BootstrapFile: /etc/hyperledger/config/genesis.block

FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: hyperledger-fabric-ordererledger

Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    Consumer:
      RetryBackoff: 2s
  Topic:
    ReplicationFactor: 3
  Verbose: false
  TLS:
    Enabled: false
    PrivateKey:
    Certificate:
    RootCAs:
  SASLPlain:
    Enabled: false
    User:
    Password:
  Version:

Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

Operations:
  ListenAddress: 0.0.0.0:9000
  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    ClientRootCAs: []

Metrics:
  Provider: prometheus
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix:

Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
