version: '3.3'

networks:
  fabric:
    driver: overlay
    attachable: true

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.9
    environment:
    - LOGSPOUT=ignore
    expose:
    - 1883
    networks:
    - fabric
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1s
      placement:
        constraints:
          - "node.labels.service==caliper1"
    volumes:
    - ~/tpcc/configs/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
