version: '3.3'

networks:
  fabric:
    driver: overlay
    attachable: true

services:
  caliper-master:
    image: klenik/caliper-fabric-1.4.17:experimental
    environment:
    - CALIPER_PROJECTCONFIG=caliper/caliper.yaml
    - LOGSPOUT=ignore
    command: launch master
    networks:
    - fabric
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - "node.labels.service==caliper1"
    volumes:
    - ~/tpcc/configs/:/hyperledger/caliper/workspace
