version: '3.3'

networks:
  fabric:
    driver: overlay
    attachable: true

services:
  kibana:
    image: kibana:7.5.1
    ports:
    # Dashboard
    - 5601:5601
    environment:
    - LOGSPOUT=ignore
    volumes:
    - ~/tpcc/configs/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
    - fabric
    deploy:
      placement:
        constraints:
          - "node.labels.service==manager"
