ca:
  name: ca.org1.example.com
  certfile: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
  keyfile: /etc/hyperledger/fabric-ca-server-config/key.pem
tls:
  enabled: true
  certfile: /etc/hyperledger/fabric-ca-server-tls/tlsca.org1.example.com-cert.pem
  keyfile: /etc/hyperledger/fabric-ca-server-tls/key.pem